services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: os2forms-api
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./app:/app/app
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
    networks:
      edge:
        aliases:
          - os2forms-api

networks:
  edge:
    external: true